version: '2'
services:
  elasticsearch:    
    container_name: ES
    image: nicolaihald/elasticsearch:latest
    #build: elasticsearch/
    #command: elasticsearch -Des.network.host=0.0.0.0 -Des.insecure.allow.root=true    
    volumes: 
      - ./elasticsearch/config:/es/config
    ports:
      - "9200:9200"
      - "9300:9300"
#    environment:
#      - PLUGINS=royrusso/elasticsearch-HQ    
    networks: 
      - elk-network

  logstash:
    container_name: "LS"
    image: nicolaihald/logstash:latest
    depends_on:
      - elasticsearch
    command: logstash -f /config/logstash.sample.conf
    #command: logstash -e 'input { stdin { } } output { stdout {} }'
    volumes:
      - ./logstash/config:/config
      - ./logstash/data:/data
    ports:
      # For collectd reception
      - "25826:25826"
    links:
      - elasticsearch
    networks: 
      - elk-network
#   
networks: 
    elk-network:
      driver: bridge

#kibana:
#  #build: kibana/
#  image: nicolaihald/kibana:latest
#  volumes:
#    - ./kibana/config/:/opt/kibana/config/
#  ports:
#    - "5601:5601"
#  links:
#    - elasticsearch#
